all:
	cc -lm -std=c99 main_linux.c AudioSink_Alsa.c ClockRecovery.c FrequencyModulator.c AudioSource_Alsa.c BandPassFilter.c FileSink.c Multiply.c BinarySlicer.c FileSource.c QuadraturDemodulator.c BitToSymbol.c FirFilter.c -o airgap

clean:
	rm airgap

