all:
	cc main_linux.c AudioSink_Alsa.c ClockRecovery.c FrequencyModulator.c AudioSource_Alsa.c ComplexToSimple.c BandPassFilter.c FileSink.c Multiply.c BinarySlicer.c FileSource.c QuadraturDemodulator.c BitToSymbol.c FirFilter.c SimpleToComplex.c -o airgap
