all:
	cc AudioSink.c ClockRecovery.c FrequencyModulator.c AudioSource.c ComplexToSimple.c BandPassFilter.c FileSink.c Multiply.c BinarySlicer.c FileSource.c QuadraturDemodulator.c BitToSymbol.c FirFilter.c SimpleToComplex.c -o airgap
